/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BanarasiRouteImport } from './routes/banarasi'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CottonSareesRouteImport } from './routes/cotton-sarees'
import { Route as DailyWearRouteImport } from './routes/daily-wear'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as FestivalRouteImport } from './routes/festival'
import { Route as HandloomRouteImport } from './routes/handloom'
import { Route as KanjivaramRouteImport } from './routes/kanjivaram'
import { Route as LinenRouteImport } from './routes/linen'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OfficeWearRouteImport } from './routes/office-wear'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PartyWearRouteImport } from './routes/party-wear'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as SilkSareesRouteImport } from './routes/silk-sarees'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountPaymentsRouteImport } from './routes/account/payments'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BanarasiRoute = BanarasiRouteImport.update({
  id: '/banarasi',
  path: '/banarasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CottonSareesRoute = CottonSareesRouteImport.update({
  id: '/cotton-sarees',
  path: '/cotton-sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyWearRoute = DailyWearRouteImport.update({
  id: '/daily-wear',
  path: '/daily-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalRoute = FestivalRouteImport.update({
  id: '/festival',
  path: '/festival',
  getParentRoute: () => rootRouteImport,
} as any)
const HandloomRoute = HandloomRouteImport.update({
  id: '/handloom',
  path: '/handloom',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjivaramRoute = KanjivaramRouteImport.update({
  id: '/kanjivaram',
  path: '/kanjivaram',
  getParentRoute: () => rootRouteImport,
} as any)
const LinenRoute = LinenRouteImport.update({
  id: '/linen',
  path: '/linen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeWearRoute = OfficeWearRouteImport.update({
  id: '/office-wear',
  path: '/office-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyWearRoute = PartyWearRouteImport.update({
  id: '/party-wear',
  path: '/party-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SilkSareesRoute = SilkSareesRouteImport.update({
  id: '/silk-sarees',
  path: '/silk-sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/banarasi': typeof BanarasiRoute
  '/best-sellers': typeof BestSellersRoute
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/cotton-sarees': typeof CottonSareesRoute
  '/daily-wear': typeof DailyWearRoute
  '/designer': typeof DesignerRoute
  '/festival': typeof FestivalRoute
  '/handloom': typeof HandloomRoute
  '/kanjivaram': typeof KanjivaramRoute
  '/linen': typeof LinenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/office-wear': typeof OfficeWearRoute
  '/order-success': typeof OrderSuccessRoute
  '/party-wear': typeof PartyWearRoute
  '/payment': typeof PaymentRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/sale': typeof SaleRoute
  '/silk-sarees': typeof SilkSareesRoute
  '/track-order': typeof TrackOrderRoute
  '/trending': typeof TrendingRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/banarasi': typeof BanarasiRoute
  '/best-sellers': typeof BestSellersRoute
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/cotton-sarees': typeof CottonSareesRoute
  '/daily-wear': typeof DailyWearRoute
  '/designer': typeof DesignerRoute
  '/festival': typeof FestivalRoute
  '/handloom': typeof HandloomRoute
  '/kanjivaram': typeof KanjivaramRoute
  '/linen': typeof LinenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/office-wear': typeof OfficeWearRoute
  '/order-success': typeof OrderSuccessRoute
  '/party-wear': typeof PartyWearRoute
  '/payment': typeof PaymentRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/sale': typeof SaleRoute
  '/silk-sarees': typeof SilkSareesRoute
  '/track-order': typeof TrackOrderRoute
  '/trending': typeof TrendingRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/banarasi': typeof BanarasiRoute
  '/best-sellers': typeof BestSellersRoute
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/cotton-sarees': typeof CottonSareesRoute
  '/daily-wear': typeof DailyWearRoute
  '/designer': typeof DesignerRoute
  '/festival': typeof FestivalRoute
  '/handloom': typeof HandloomRoute
  '/kanjivaram': typeof KanjivaramRoute
  '/linen': typeof LinenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/office-wear': typeof OfficeWearRoute
  '/order-success': typeof OrderSuccessRoute
  '/party-wear': typeof PartyWearRoute
  '/payment': typeof PaymentRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/sale': typeof SaleRoute
  '/silk-sarees': typeof SilkSareesRoute
  '/track-order': typeof TrackOrderRoute
  '/trending': typeof TrendingRoute
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/banarasi'
    | '/best-sellers'
    | '/bridal'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/collections'
    | '/cotton-sarees'
    | '/daily-wear'
    | '/designer'
    | '/festival'
    | '/handloom'
    | '/kanjivaram'
    | '/linen'
    | '/new-arrivals'
    | '/office-wear'
    | '/order-success'
    | '/party-wear'
    | '/payment'
    | '/payment-failed'
    | '/sale'
    | '/silk-sarees'
    | '/track-order'
    | '/trending'
    | '/wedding'
    | '/wishlist'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/admin/settings'
    | '/auth/callback'
    | '/product/$id'
    | '/account/'
    | '/admin/'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/banarasi'
    | '/best-sellers'
    | '/bridal'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/collections'
    | '/cotton-sarees'
    | '/daily-wear'
    | '/designer'
    | '/festival'
    | '/handloom'
    | '/kanjivaram'
    | '/linen'
    | '/new-arrivals'
    | '/office-wear'
    | '/order-success'
    | '/party-wear'
    | '/payment'
    | '/payment-failed'
    | '/sale'
    | '/silk-sarees'
    | '/track-order'
    | '/trending'
    | '/wedding'
    | '/wishlist'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/admin/settings'
    | '/auth/callback'
    | '/product/$id'
    | '/account'
    | '/admin'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/banarasi'
    | '/best-sellers'
    | '/bridal'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/collections'
    | '/cotton-sarees'
    | '/daily-wear'
    | '/designer'
    | '/festival'
    | '/handloom'
    | '/kanjivaram'
    | '/linen'
    | '/new-arrivals'
    | '/office-wear'
    | '/order-success'
    | '/party-wear'
    | '/payment'
    | '/payment-failed'
    | '/sale'
    | '/silk-sarees'
    | '/track-order'
    | '/trending'
    | '/wedding'
    | '/wishlist'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/admin/settings'
    | '/auth/callback'
    | '/product/$id'
    | '/account/'
    | '/admin/'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BanarasiRoute: typeof BanarasiRoute
  BestSellersRoute: typeof BestSellersRoute
  BridalRoute: typeof BridalRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  CottonSareesRoute: typeof CottonSareesRoute
  DailyWearRoute: typeof DailyWearRoute
  DesignerRoute: typeof DesignerRoute
  FestivalRoute: typeof FestivalRoute
  HandloomRoute: typeof HandloomRoute
  KanjivaramRoute: typeof KanjivaramRoute
  LinenRoute: typeof LinenRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OfficeWearRoute: typeof OfficeWearRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PartyWearRoute: typeof PartyWearRoute
  PaymentRoute: typeof PaymentRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  SaleRoute: typeof SaleRoute
  SilkSareesRoute: typeof SilkSareesRoute
  TrackOrderRoute: typeof TrackOrderRoute
  TrendingRoute: typeof TrendingRoute
  WeddingRoute: typeof WeddingRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banarasi': {
      id: '/banarasi'
      path: '/banarasi'
      fullPath: '/banarasi'
      preLoaderRoute: typeof BanarasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotton-sarees': {
      id: '/cotton-sarees'
      path: '/cotton-sarees'
      fullPath: '/cotton-sarees'
      preLoaderRoute: typeof CottonSareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-wear': {
      id: '/daily-wear'
      path: '/daily-wear'
      fullPath: '/daily-wear'
      preLoaderRoute: typeof DailyWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival': {
      id: '/festival'
      path: '/festival'
      fullPath: '/festival'
      preLoaderRoute: typeof FestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handloom': {
      id: '/handloom'
      path: '/handloom'
      fullPath: '/handloom'
      preLoaderRoute: typeof HandloomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanjivaram': {
      id: '/kanjivaram'
      path: '/kanjivaram'
      fullPath: '/kanjivaram'
      preLoaderRoute: typeof KanjivaramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linen': {
      id: '/linen'
      path: '/linen'
      fullPath: '/linen'
      preLoaderRoute: typeof LinenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-wear': {
      id: '/office-wear'
      path: '/office-wear'
      fullPath: '/office-wear'
      preLoaderRoute: typeof OfficeWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-wear': {
      id: '/party-wear'
      path: '/party-wear'
      fullPath: '/party-wear'
      preLoaderRoute: typeof PartyWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silk-sarees': {
      id: '/silk-sarees'
      path: '/silk-sarees'
      fullPath: '/silk-sarees'
      preLoaderRoute: typeof SilkSareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BanarasiRoute: BanarasiRoute,
  BestSellersRoute: BestSellersRoute,
  BridalRoute: BridalRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  CottonSareesRoute: CottonSareesRoute,
  DailyWearRoute: DailyWearRoute,
  DesignerRoute: DesignerRoute,
  FestivalRoute: FestivalRoute,
  HandloomRoute: HandloomRoute,
  KanjivaramRoute: KanjivaramRoute,
  LinenRoute: LinenRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OfficeWearRoute: OfficeWearRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PartyWearRoute: PartyWearRoute,
  PaymentRoute: PaymentRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  SaleRoute: SaleRoute,
  SilkSareesRoute: SilkSareesRoute,
  TrackOrderRoute: TrackOrderRoute,
  TrendingRoute: TrendingRoute,
  WeddingRoute: WeddingRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
